#!/bin/bash

# Default command
# export FZF_DEFAULT_COMMAND='( fd -t f -E ".*" -L . ; fd -t f -H -E ".git/*" -L . ) \
#   2> /dev/null'

# export FZF_DEFAULT_OPTS="
#   --bind 'ctrl-j:down'
#   --bind 'ctrl-k:up'
#   --bind 'ctrl-o:execute(nvim.appimage {})+abort'
#   --bind '?:toggle-preview'
#   --bind 'alt-j:preview-page-down'
#   --bind 'alt-k:preview-page-up'
#   --height 40% --reverse --border
#   --preview 'bat --style=numbers --color=always {}'
#   --preview-window=right:60%:hidden:wrap:border:sharp
#   --margin 1%
#   --color=fg:#908caa,bg:#191724,hl:#ebbcba
# 	--color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
# 	--color=border:#403d52,header:#31748f,gutter:#191724
# 	--color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
# 	--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

# CTRL-T - Paste the selected files and directories onto the command-line
export FZF_CTRL_T_COMMAND='( fd -t f -E ".*" -L . ; fd -t f -H -E ".git/*" -L . ) \
  2> /dev/null'

export FZF_CTRL_T_OPTS="
  --bind 'ctrl-j:down'
  --bind 'ctrl-k:up'
  --bind '?:toggle-preview'
  --bind 'alt-j:preview-page-down'
  --bind 'alt-k:preview-page-up'
  --height 40% --reverse --border
  --preview 'bat --style=numbers,header-filename --color=always {}'
  --preview-window=right:60%:hidden:wrap:border:sharp
  --margin 1%
  --color=fg:#908caa,bg:#191724,hl:#ebbcba
	--color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
	--color=border:#403d52,header:#31748f,gutter:#191724
	--color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
	--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

# export FZF_CTRL_T_OPTS="$FZF_DEFAULT_OPTS"

# ALT-C command to change directory
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"

export FZF_ALT_C_OPTS="
  --bind 'enter:execute(cd -s {})+abort'
  --bind 'ctrl-j:down'
  --bind 'ctrl-k:up'
  --height 40% --reverse --border
  --preview 'erd -C force -I -L 2 --suppress-size {} | head -100'
  --preview-window=right:50%:nohidden:wrap:border:sharp
  --margin 1%
  --color=fg:#908caa,bg:#191724,hl:#ebbcba
  --color=fg+:#e0def4,bg+:#26233a,hl+:#ebbcba
  --color=border:#403d52,header:#31748f,gutter:#191724
  --color=spinner:#f6c177,info:#9ccfd8,separator:#403d52
  --color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa"

export FZF_TMUX=1
